name: 'SmartBugs Local Static Analysis'
description: 'Run SmartBugs static analysis tools on Solidity Contracts in repo. Tools available: Honeybadger, Maian, Manticore, Mythril, Osiris, Oyente, Securify, Slither, SmartCheck, Solhint.'
inputs:
  tool:
    description: 'Specify tools to run the analysis separated by a semi-colon. By default all tools are run. Example: "oyente,mythril,maian".'
    required: false
    default: 'mythril,slither'
runs:
  using: "composite"
  steps:
  - name: "Setup SmartBugs"
    shell: bash
    run: |
          git clone --single-branch --branch module-capability https://github.com/smartbugs/smartbugs.git
          python3 -m pip install -r smartbugs/requirements.txt
          rm -r smartbugs/dataset/
  - name: Run smartbugs static analysis
    shell: bash
    run: |
          python3 smartbugs/smartBugs.py --tool conkas --file ./ --unique-sarif-output
          sarif_file="$(basename smartbugs/results/*.sarif)"
          mv smartbugs/results/$sarif_file smartbugs/results/results.sarif
  - name: Upload SARIF file
    uses: github/codeql-action/upload-sarif@v1
    with:
        sarif_file: smartbugs/results/results.sarif
